# Linting.

name: Linting
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black
        pip install flake8
        pip install pre-commit
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --max-line-length=79 --ignore=E501,W503,W504,W605,E203 --exclude=.codesandbox,.db,.conda,.env
    - name: Lint with black
      run: |
        black . --check --verbose --line-length 79
